### ISSUE TITLE
Installing DareBlopy on Windows

### ISSUE THREAD

**Issue by chinasilva** [podgorskiy/ALAE#29]
i can't pip DareBlopy in windows,how to repair it ,thank u

**Comment by podgorskiy** [comment]
Currently, there is no DareBlopy for windows.
Though, it is not needed for running demos or producing figures.

I'll try to make a windows build soonish.

**Comment by podgorskiy** [comment]
Fixed in https://github.com/podgorskiy/DareBlopy/commit/66480d08a517a0ec525e66f85f3f66171ac8b763 https://github.com/podgorskiy/DareBlopy/commit/33dd413e488ddcdcd227b988f607529f80261d4c https://github.com/podgorskiy/DareBlopy/commit/548fc099f9172cb76f3f2e69a1d9d101045b4835  https://github.com/podgorskiy/DareBlopy/commit/03b61b484b772056e99a74a13646b1a8057f6163

Uploaded dareblopy package to pypi. Now you can do `pip install dareblopy` on Windows

Python2.7 version is not working properly, but I'm not going to fix that.
